development:
  adapter: postgresql
  encoding: unicode
  database: moneystat_dev
  pool: 5
  username: le.ngoc.cuong
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: moneystat_test
  pool: 5
  username: le.ngoc.cuong
  password:
